FROM apache/airflow:2.7.0


USER root

RUN sudo apt-get update
RUN sudo  apt-get install -y openjdk-11-jre
RUN sudo apt-get install wget
RUN sudo apt-get clean
RUN sudo rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH

USER airflow

COPY requirement.txt .
COPY variable.json .
RUN pip install -r requirement.txt
RUN wget   https://jdbc.postgresql.org/download/postgresql-42.6.0.jar -P /home/airflow/.local/lib/python3.8/site-packages/pyspark/jars/ 
RUN wget   https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar  -P /home/airflow/.local/lib/python3.8/site-packages/pyspark/jars/ 
RUN wget   https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.123/aws-java-sdk-bundle-1.12.123.jar -P /home/airflow/.local/lib/python3.8/site-packages/pyspark/jars/ 

ENV PYSPARK_PYTHON=python3
#ENV SPARK_HOME=/path/to/spark

